/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ClaimRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "claims" | "fileClaim" | "nextClaimId" | "verifyClaim"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ClaimFiled" | "ClaimVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claims",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fileClaim", values: [string]): string;
  encodeFunctionData(
    functionFragment: "nextClaimId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyClaim",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "claims", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fileClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextClaimId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyClaim",
    data: BytesLike
  ): Result;
}

export namespace ClaimFiledEvent {
  export type InputTuple = [
    id: BigNumberish,
    claimant: AddressLike,
    filecoinCid: string
  ];
  export type OutputTuple = [id: bigint, claimant: string, filecoinCid: string];
  export interface OutputObject {
    id: bigint;
    claimant: string;
    filecoinCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimVerifiedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClaimRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ClaimRegistry;
  waitForDeployment(): Promise<this>;

  interface: ClaimRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claims: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        id: bigint;
        claimant: string;
        filecoinCid: string;
        timestamp: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  fileClaim: TypedContractMethod<
    [_filecoinCid: string],
    [bigint],
    "nonpayable"
  >;

  nextClaimId: TypedContractMethod<[], [bigint], "view">;

  verifyClaim: TypedContractMethod<
    [_claimId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claims"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        id: bigint;
        claimant: string;
        filecoinCid: string;
        timestamp: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fileClaim"
  ): TypedContractMethod<[_filecoinCid: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "nextClaimId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyClaim"
  ): TypedContractMethod<[_claimId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "ClaimFiled"
  ): TypedContractEvent<
    ClaimFiledEvent.InputTuple,
    ClaimFiledEvent.OutputTuple,
    ClaimFiledEvent.OutputObject
  >;
  getEvent(
    key: "ClaimVerified"
  ): TypedContractEvent<
    ClaimVerifiedEvent.InputTuple,
    ClaimVerifiedEvent.OutputTuple,
    ClaimVerifiedEvent.OutputObject
  >;

  filters: {
    "ClaimFiled(uint256,address,string)": TypedContractEvent<
      ClaimFiledEvent.InputTuple,
      ClaimFiledEvent.OutputTuple,
      ClaimFiledEvent.OutputObject
    >;
    ClaimFiled: TypedContractEvent<
      ClaimFiledEvent.InputTuple,
      ClaimFiledEvent.OutputTuple,
      ClaimFiledEvent.OutputObject
    >;

    "ClaimVerified(uint256)": TypedContractEvent<
      ClaimVerifiedEvent.InputTuple,
      ClaimVerifiedEvent.OutputTuple,
      ClaimVerifiedEvent.OutputObject
    >;
    ClaimVerified: TypedContractEvent<
      ClaimVerifiedEvent.InputTuple,
      ClaimVerifiedEvent.OutputTuple,
      ClaimVerifiedEvent.OutputObject
    >;
  };
}
